import Head from 'next/head'
import { Inter } from '@next/font/google'
import Portfolio from '../../components/Portfolio'

const inter = Inter({ subsets: ['latin'] })

export default function projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Portfolio/>
    </>
  )
}
