import React from "react";
import style from "../styles/Header.module.scss";
import Github from "./imagesjs/Github"
import LinkedIn from "./imagesjs/LinkedIn"
import Head from "next/head";
import { useState, useEffect } from "react";

export default function Header() {

  const [title, setTitle] = useState("Bharat Soni");
  const [icon, setIcon] = useState("/favicon.ico");

  // User has switched back to the tab
  const onFocus = () => {
    setTitle("Bharat Soni");
    setIcon("/favicon.ico");
  };

  // User has switched away from the tab (AKA tab is hidden)
  const onBlur = () => {
    setTitle("come back baby🥺");
    setIcon("/favicon.jpeg");
  };

  useEffect(() => {
    window.addEventListener("focus", onFocus);
    window.addEventListener("blur", onBlur);
    // Calls onFocus when the window first loads
    onFocus();
    // Specify how to clean up after this effect:
    return () => {
      window.removeEventListener("focus", onFocus);
      window.removeEventListener("blur", onBlur);
    };
  }, []);

  return (
    <>
    <Head>
        <title>{title??"Bharat Soni"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={icon} />
      </Head>
    <header role="header" className={style.Header}>
      <nav className={style.MainMenu}>
        <ul>
          <li>
            <a
              href="https://github.com/bharatchills"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Github />
            </a>
          </li>
          <li>
            <a
              href="https://www.linkedin.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <LinkedIn />
            </a>
          </li>
        </ul>
      </nav>
    </header>
    </>
  );
}
