import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.scss'
import Chat from '../components/Chat'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [title, setTitle] = useState('Bharat Soni');
  const [icon, setIcon] = useState('/favicon.ico');

  // User has switched back to the tab
const onFocus = () => {
  setTitle('Bharat Soni');
  setIcon('/favicon.ico');
};

// User has switched away from the tab (AKA tab is hidden)
const onBlur = () => {
  setTitle('Wow! so smart');
  setIcon('/favicon.jpeg');
};


 useEffect(() => {
        window.addEventListener("focus", onFocus);
        window.addEventListener("blur", onBlur);
        // Calls onFocus when the window first loads
        onFocus();
        // Specify how to clean up after this effect:
        return () => {
            window.removeEventListener("focus", onFocus);
            window.removeEventListener("blur", onBlur);
        };
  }, []);

  return (
    <>
      <Head >
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={icon} />
      </Head>
      <Chat/>
    </>
  )
}
